/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estancias2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miguelangel
 */
public class MarcarAsistencia extends javax.swing.JFrame {

    
    String CLAVE,nombre_evento;
    ArrayList<String> CLAVE_sql;
    public MarcarAsistencia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    MarcarAsistencia(String CLAVE_x){
        initComponents();
        this.setLocationRelativeTo(null);
        
        CLAVE = CLAVE_x;
        Busqueda();
    }
    
    //realizar busqueda de evento donde se encontrara el evento seleccionado en la interfaz anterior
    void Busqueda(){
        try {
            DefaultTableModel model= new DefaultTableModel();
            
            model.addColumn("Nombre");
            model.addColumn("Capacidad");
            model.addColumn("Fecha");
            model.addColumn("Hora de inicio");
            model.addColumn("Hora de fin");
            model.addColumn("Direccion");


            busqueda_table.setModel(model);
            
            Date fecha_actual = new Date();
            
            String consultar="SELECT nombre,capacidad,fecha,hora_inicio,hora_fin,calle,numero,cp,colonia FROM evento WHERE clave='"+CLAVE+"'";

            String []datos= new String[6];
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(consultar);
            
            while(rs.next()){
                nombre_evento = rs.getString(1);
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]="calle "+rs.getString(6)+", numero "+rs.getString(7)+", C.P "+rs.getString(8)+", colonia "+rs.getString(9);
             
                model.addRow(datos);
            }
          //  tbpro.setModel(model);
        } catch (SQLException ex) {
            showMessageDialog(null, "No hay eventos disponibles.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        matricula_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        busqueda_table = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuario_table = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Asistencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1270, 20));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton7.setText("Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 120, 40));

        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 120, 40));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Evento a asistir:");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        matricula_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matricula_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_txtActionPerformed(evt);
            }
        });
        getContentPane().add(matricula_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 230, 30));

        busqueda_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        busqueda_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(busqueda_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 1150, 70));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Usuario que asistira:");
        jLabel19.setToolTipText("");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Matricula:");
        jLabel20.setToolTipText("");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        usuario_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(usuario_table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 1150, 70));

        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton9.setText("Dar Asistencia");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t7hNp4Q.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MenuUsuario obj2 = new MenuUsuario();
        obj2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void matricula_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula_txtActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            if("".equals(matricula_txt.getText())){
                throw new Exception();
            }else{
                try {
                    String matricula = matricula_txt.getText();
                    
                    DefaultTableModel model= new DefaultTableModel();

                    model.addColumn("Matricula");
                    model.addColumn("Nombre(s)");
                    model.addColumn("Apellido Paterno");
                    model.addColumn("Apellido Materno");
                    model.addColumn("E-mail");
                    model.addColumn("Telefono");
                    model.addColumn("Hora");


                    usuario_table.setModel(model);
                    CLAVE_sql = new ArrayList();

                    Date fecha_actual = new Date();

                    String consultar="SELECT matricula,nombre,apaterno,amaterno,email,telefono FROM usuario WHERE matricula='"+matricula+"'";

                    String []datos= new String[7];
                    
                    Statement st=cn.createStatement();
                    ResultSet rs=st.executeQuery(consultar);

                    while(rs.next()){
                        CLAVE_sql.add(rs.getString(1));
                        datos[0]=rs.getString(1);
                        datos[1]=rs.getString(2);
                        datos[2]=rs.getString(3);
                        datos[3]=rs.getString(4);
                        datos[4]=rs.getString(5);
                        datos[5]=rs.getString(6);
                        datos[6]=fecha_actual.toString();
                        model.addRow(datos);
                    }
                    
                    if(!(CLAVE_sql.contains(matricula))){
                        throw new Exception();
                    }else{                   
                        java.sql.Time time = new java.sql.Time(fecha_actual.getTime());
                        //cada vez que se marca asistencia, se disminuye la capacidad para usuarios que posee el evento
                        PreparedStatement pst2 = cn.prepareStatement("UPDATE evento SET capacidad = capacidad - 1 WHERE clave = '"+CLAVE+"'");
                        pst2.executeUpdate();
                        //se marca asistencia dentro de la tabla asistencia en la base de datos deacuerdo al evento seleccionado y a la matricula del
                        //usuario que ha sido ingresada en el campo de texto
                        PreparedStatement pst = cn.prepareStatement("INSERT INTO asistencia VALUES(?,?,?,?)");
                        pst.setString(1, CLAVE);
                        pst.setString(2, nombre_evento);
                        pst.setString(3, matricula);
                        pst.setTime(4, (Time) time);
                        
                        pst.executeUpdate();
                        
                        showMessageDialog(null, "Registro de Asistencia Exitoso");
                        ListaEventos lista = new ListaEventos();
                        lista.setVisible(true);
                        dispose();
                    }
                  //  tbpro.setModel(model);
                } catch (Exception ex) {
                    showMessageDialog(null, "No existe un usuario con esa matricula.");
                }
            }
        }catch(Exception e){
            showMessageDialog(null, "Favor de Ingresar Matricula.");
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcarAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable busqueda_table;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField matricula_txt;
    private javax.swing.JTable usuario_table;
    // End of variables declaration//GEN-END:variables
    Conection cc = new Conection();
    Connection cn = cc.conexion();
}
