package estancias2;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author miguelangel
 */
import java.util.Date;
public class RegistrarEvento extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEvento
     */
    String nombre,calle,numero,cp,colonia,clave;
    int capacidad;
    String dateInString,timeInString_inicio,timeInString_fin; 
    // hora inicio, hora fin.

    public RegistrarEvento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calle_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        numero_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cp_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        colonia_txt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        clave_txt = new javax.swing.JTextField();
        capacidad_txt = new javax.swing.JTextField();
        inicio_txt = new javax.swing.JTextField();
        fin_txt = new javax.swing.JTextField();
        fecha_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1270, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        nombre_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 390, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Calle:");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, -1, -1));

        calle_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calle_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calle_txtActionPerformed(evt);
            }
        });
        getContentPane().add(calle_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 390, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Numero:");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        numero_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(numero_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 160, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("C.P:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, -1, -1));

        cp_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, 150, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Colonia:");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        colonia_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(colonia_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 390, 30));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("GUARDAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 230, 40));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Menu");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 130, 40));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, 120, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Evento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Clave:");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Capacidad:");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hora de inicio:");
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha:");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Hora de fin:");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ingresar los datos del evento a registrar");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        clave_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clave_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(clave_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 390, 30));

        capacidad_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        capacidad_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(capacidad_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 330, 30));

        inicio_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inicio_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(inicio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 330, 30));

        fin_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fin_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 330, 30));

        fecha_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fecha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t7hNp4Q.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calle_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calle_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calle_txtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{
            //verifica que no existan campos vacios
            if("".equals(nombre_txt.getText())||"".equals(capacidad_txt.getText())||"".equals(clave_txt.getText())||"".equals(fecha_txt.getText())||"".equals(calle_txt.getText())||"".equals(numero_txt.getText())||"".equals(cp_txt.getText())||"".equals(colonia_txt.getText())||"".equals(inicio_txt.getText())||"".equals(fin_txt.getText())){
                throw new Exception();
            }else{
                clave = clave_txt.getText();
                nombre = nombre_txt.getText();
                capacidad = Integer.parseInt(capacidad_txt.getText());
                
                //////////////////////////////////////////////////////////////////////////////////
                SimpleDateFormat formatter_date = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat formatter_time = new SimpleDateFormat("HH:mm");
                
                dateInString = fecha_txt.getText();
                Date date = formatter_date.parse(dateInString);
                
                timeInString_inicio = inicio_txt.getText();
                Date time_inicio = formatter_time.parse(timeInString_inicio);
                
                timeInString_fin = fin_txt.getText();
                Date time_fin = formatter_time.parse(timeInString_fin);
                //////////////////////////////////////////////////////////////////////////////////
                //guardar informacion de los campos en las variables correspondientes
                calle = calle_txt.getText();
                numero = numero_txt.getText();
                cp = cp_txt.getText();
                colonia = colonia_txt.getText();

                String sql;
                ArrayList<String> id = new ArrayList<String>();

                try{
                    //consulta para obtener los eventos con la misma clave ingresada, esto permite darle a negar al administrador que registre eventos si 
                    //ya existe un evento con la misma clave
                    sql="SELECT clave FROM evento WHERE clave='"+clave+"'";
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                        id.add(rs.getString(1));
                    }
                }catch(Exception e){
                }

                if(id.contains(clave)){
                    showMessageDialog(null, "Favor de Ingresar otra Clave.");
                }else{
                    try{
                        java.sql.Date date1 = new java.sql.Date(date.getTime());
                        java.sql.Time time_inicio1 = new java.sql.Time(time_inicio.getTime());
                        java.sql.Time time_fin1 = new java.sql.Time(time_fin.getTime());
                        
                        
                        //si no exite otro evento con la misma clave, se realiza la insercion de datos en la 
                        //tabla evento de la base de datos
                        PreparedStatement pst = cn.prepareStatement("INSERT INTO evento VALUES(?,?,?,?,?,?,?,?,?,?)");//10
                        
                        pst.setString(1, clave);
                        pst.setString(2, nombre);
                        pst.setInt(3, capacidad);
                        pst.setDate(4, date1);
                        pst.setTime(5, (Time) time_inicio1);
                        pst.setTime(6, (Time) time_fin1);
                        pst.setString(7, calle);
                        pst.setString(8, numero);
                        pst.setString(9, cp);
                        pst.setString(10, colonia);
                        
                        pst.executeUpdate();
                        showMessageDialog(null, "Registro exitoso!!");
                        Inicio inicio = new Inicio();
                        inicio.setVisible(true);
                        dispose();
                    }catch(Exception e){
                        showMessageDialog(null, "Error en Base de datos");
                    }
                }
            }
        }catch(Exception e){
            showMessageDialog(null, "Favor de llenar todos los campos");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        estancias2.MenuAdmin p1 = new estancias2.MenuAdmin();
        p1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calle_txt;
    private javax.swing.JTextField capacidad_txt;
    private javax.swing.JTextField clave_txt;
    private javax.swing.JTextField colonia_txt;
    private javax.swing.JTextField cp_txt;
    private javax.swing.JTextField fecha_txt;
    private javax.swing.JTextField fin_txt;
    private javax.swing.JTextField inicio_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTextField numero_txt;
    // End of variables declaration//GEN-END:variables
    Conection cc = new Conection();
    Connection cn = cc.conexion();
}
