/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estancias2;

import java.sql.*;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author miguelangel
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    String matricula,nombre,apaterno,amaterno,email,telefono,contraseña;
    
    public RegistrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contraseña_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        apaterno_txt = new javax.swing.JTextField();
        amaterno_txt = new javax.swing.JTextField();
        telefono_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        matricula_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1270, 20));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("GUARDAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 230, 40));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Menu");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 130, 40));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, 120, 40));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ingresar los datos del nuevo usuario a registrar");
        jLabel18.setToolTipText("");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Matricula:");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        contraseña_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contraseña_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(contraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 400, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre(s):");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        nombre_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 400, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellido Paterno:");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Apellido Materno:");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E-mail:");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefono:");
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        apaterno_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apaterno_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(apaterno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 320, 30));

        amaterno_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amaterno_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(amaterno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 320, 30));

        telefono_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 400, 30));

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 400, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Contraseña:");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        matricula_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matricula_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matricula_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 400, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t7hNp4Q.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{
            //verifica que no existan campos vacios
            if("".equals(matricula_txt.getText())||"".equals(nombre_txt.getText())||"".equals(apaterno_txt.getText())||"".equals(amaterno_txt.getText())||"".equals(email_txt.getText())||"".equals(telefono_txt.getText())||"".equals(contraseña_txt.getText())){
                throw new Exception();
            }else{
                // se guarda la informacion dentro de las variables correspondientes
                matricula = matricula_txt.getText();
                contraseña = contraseña_txt.getText();
                nombre = nombre_txt.getText();
                apaterno = apaterno_txt.getText();
                amaterno = amaterno_txt.getText();
                email = email_txt.getText();
                telefono = telefono_txt.getText();

                String sql;
                ArrayList<String> id = new ArrayList<String>();

                try{
                    //consultar para saber si no existe otro usuario con la misma matricula
                    sql="SELECT matricula FROM usuario WHERE matricula='"+matricula+"'";
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                        id.add(rs.getString(1));
                    }
                }catch(Exception e){
                }

                if(id.contains(matricula)){
                    showMessageDialog(null, "Ya existe un usuario con esa matricula.");
                }else{
                    try{
                        //se realiza la insercion de datos en la tabla usuario
                        PreparedStatement pst = cn.prepareStatement("INSERT INTO usuario VALUES(?,?,?,?,?,?,?,?)");//8
                        //PreparedStatement pst = cn.prepareStatement("INSERT INTO places (rfc,nombre,tipo,descripcion,calle,numero,cp,colonia,lunes_a,lunes_c,martes_a,martes_c,miercoles_a,miercoles_c,jueves_a,jueves_c,viernes_a,viernes_c,sabado_a,sabado_c,domingo_a,domingo_c,usuario,ruta) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        //PreparedStatement pst = cn.prepareStatement("INSERT INTO places VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        //PreparedStatement pst = cn.prepareStatement("INSERT INTO places(rfc,nombre,tipo,descripcion,calle,numero,cp,colonia,lunes_a,lunes_c,martes_a,martes_c,miercoles_a,miercoles_c,jueves_a,jueves_c,viernes_a,viernes_c,sabado_a,sabado_c,domingo_a,domingo_c,usuario,ruta,imagen) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        pst.setString(1, matricula);
                        pst.setString(2, contraseña);
                        pst.setString(3, nombre);
                        pst.setString(4, apaterno);
                        pst.setString(5, amaterno);
                        pst.setString(6, email);
                        pst.setString(7, telefono);
                        
                        pst.setString(8, "C:\\Users\\miguelangel\\Desktop\\Estancias ll\\"+matricula+".png"); //ruta del qr correspondiente al usuario que se desea registrar
                        GenerarQR x = new GenerarQR();
                        x.QR(matricula);

                        pst.executeUpdate();
                        showMessageDialog(null, "Registro exitoso!!");
                        Inicio inicio = new Inicio();
                        inicio.setVisible(true);
                        dispose();
                    }catch(Exception e){
                        showMessageDialog(null, "Error en Base de datos");
                    }
                }
            }
        }catch(Exception e){
            showMessageDialog(null, "Favor de llenar todos los campos");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        estancias2.MenuAdmin p1 = new estancias2.MenuAdmin();
        p1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amaterno_txt;
    private javax.swing.JTextField apaterno_txt;
    private javax.swing.JTextField contraseña_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField matricula_txt;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables
    Conection cc = new Conection();
    Connection cn = cc.conexion();
}
